### ISSUE TITLE
Cannot connect wallet with chrome

### ISSUE THREAD

**Issue by ricky321u** [pendle-finance/pendle-core-v2-public#8]
Uncaught (in promise) TypeError: 'get' on proxy: property 'request' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'async function(...i){if(!n.currentWalletExtension&&i[0]?.method==="eth_requestAccounts"){const o=await n._cdcPr...<omitted>...)}' but got 'async function(...i){if(!n.currentWalletExtension&&i[0]?.method==="eth_requestAccounts"){const o=await n._cdcPr...<omitted>...)}')
    at checkProviderIdentity (index-5608af86.js:658:22493)
    at isWalletAvailable (index-5608af86.js:658:42451)
    at index-5608af86.js:658:43013
    at Array.reduce (<anonymous>)
    at index-5608af86.js:658:42880
    at index-5608af86.js:463:24235
    at Array.reduce (<anonymous>)
    at initializeWalletModules (index-5608af86.js:463:24209)
    at setWalletModules (index-5608af86.js:463:23789)
    at Object.connect$1 [as connectWallet] (index-5608af86.js:463:25055)
    at Proxy.connectWallet (index-5608af86.js:722:93274)
    at index-5608af86.js:1:104730
    at callWithErrorHandling (index-5608af86.js:1:21207)
    at callWithAsyncErrorHandling (index-5608af86.js:1:21343)
    at HTMLButtonElement.n6 (index-5608af86.js:1:87377)
    at HTMLButtonElement.r6 (index-5608af86.js:16:2172)

**Comment by ayobuenavista** [comment]
Please do not submit support requests to our public repo. Kindly go to our Discord.
